name: Maven Run for Production Environment

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Workflow Telemetry
        uses: thundra-io/workflow-telemetry-action@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   continue-on-error: true
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-package-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-package
      - name: Thundra Maven Test Instrumentation Action
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: ${{ secrets.THUNDRA_DEMO_ACCOUNT_APIKEY_PROD }}
          project_id: ${{ secrets.THUNDRA_DEMO_TODO_APP_PROJECTID_PROD }}
          command: mvn -B clean package
        env:
          THUNDRA_BROWSERSTACK_ENABLED: false
          THUNDRA_BROWSERSTACK_USERNAME: ${{ secrets.THUNDRA_BROWSERSTACK_USERNAME }}
          THUNDRA_BROWSERSTACK_ACCESSKEY: ${{ secrets.THUNDRA_BROWSERSTACK_ACCESSKEY }}
